##############################################
#
#  Helix, Orion, APAC and PC settings
#
INCLUDE   = -I../ -I../../GSnew

.SUFFIXES: .f .o
.f.o:
	$(COMPILER) $(INCLUDE) $(PREP) $(CFLAGS) $(OPT) -c $<

OBJ   = loops.o

all : $(OBJ)



